# SPDX-FileCopyrightText: 2024 Skatteverket - Swedish Tax Agency
#
# SPDX-License-Identifier: CC0-1.0

---
version: 2
updates:
  - package-ecosystem: npm
    directories:
      - "/"
      - "/apps/desktop"
      - "/apps/web"
      - "/packages/config-tailwind"
      - "/packages/config-typescript"
      - "/packages/react-mla"
      - "/packages/webcomponent-mla"
      - "/tools/icon-scripts"
    schedule:
      interval: "daily"

    # Configure commit messages to follow conventional commit format
    commit-message:
      prefix: "fix"
      include: "scope"

    # Configure the format of pull request branch names
    pull-request-branch-name:
      separator: "-"

    # Automatically add these labels to created pull requests
    labels:
      - "dependencies"
      - "npm"

    # Group definitions for related dependencies
    groups:
      prod-npm-minor-dependencies:
        dependency-type: "production"    
        update-types:
          - "minor"
          - "patch"
      dev-npm-minor-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]

  # Configuration for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"

    # Configure commit messages to follow conventional commit format
    commit-message:
      prefix: "fix"
      include: "scope"

    # Configure the format of pull request branch names
    pull-request-branch-name:
      separator: "-"

    # Automatically add these labels to created pull requests
    labels:
      - "dependencies"
      - "actions"

    groups:
      actions-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
