# SPDX-FileCopyrightText: 2024 Skatteverket - Swedish Tax Agency
#
# SPDX-License-Identifier: CC0-1.0

---
policies:
  - type: commit
    spec:
      dco: true
      gpg:
        required: true
      header:
        length: 90
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: false
      conventional:
        types: ["chore", "docs", "perf", "refactor", "style", "test", "release"]
        scopes: [".*"]
