# SPDX-FileCopyrightText: 2023 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

---
name: Conform DCO (--Sign-off)
on: [workflow_call] # yamllint disable-line rule:truthy

jobs:
  signoff:
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup main branch without switching current branch
        run: git fetch origin main:main

      - name: Conform Action
        uses: docker://ghcr.io/siderolabs/conform:v0.1.0-alpha.27-2-g7d9dec0
        with:
          args: "enforce --base-branch=main"